
//Dispatch Alerta
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'



//Dispatch Base de datos 
export const REGISTRO_EXITOSO ='REGISTRO_EXITOSO'
export const REGISTRO_ERROR ='REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_ERROR = ' LOGIN_ERROR'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const CERRAR_SESION = 'CERRAR_SESION'


//Dispatch Proyectos 

export const ACTIVAR_FORMULARIO = 'ACTIVAR_FORMULARIO'
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO'
export const CARGAR_PROYECTOS = 'CARGAR_PROYECTOS'
export const CARGAR_PROYECTOACTUAL = 'CARGAR_PROYECTOACTUAL'
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO'

//Dispatch Tareas
export const CARGAR_TAREAS = 'CARGAR_TAREAS'
export const AGREGAR_TAREA = 'AGREGAR_TAREA'
export const EDITAR_TAREA = 'EDITAR_TAREA'
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA'
export const FORMULARIO_EDITAR = 'FORMULARIO_EDITAR'
